### ISSUE TITLE
Filters->Color Effect->Vignette not work

### ISSUE THREAD

**Issue by euheny** [gfycat/gifbrewery#24]
Version 3.3.1 (34204)
Filter vignette not work (sliders not affect image)

**Comment by hellopatrick** [comment]
@Fixed in latest 3.4 build by switching from CIVignette to CIVignetteEffect.

For GIF Brewery 3.4, setting the filter's "center" as the video's current center.  If you resize after that, the center will no longer be in the right spot, so apply the vignette after any resizes (crops and other filters are okay).

**Comment by euheny** [comment]
![image](https://cloud.githubusercontent.com/assets/1460508/22479801/2ec3b38e-e800-11e6-9dbe-b73a824ae8df.png)
not help "apply the vignette as the last effect".

**Comment by hellopatrick** [comment]
Yes, it is broken in GIF Brewery 3.3.1.

I've fixed in GIF Brewery 3.4 by switching to a different version of the vignette filter, which Apple provides.

In the next update, you'll generally want to apply the vignette last.

**Comment by euheny** [comment]
Sorry, but vignette as last filter is not good solution. If user want apply photo effect with color (process for example) - vignette lost this and keep grayscale.

**Comment by hellopatrick** [comment]
I should be more clear, you shouldn't apply a *resize* filter after the vignette. You may apply any other image filter before or after the vignette.

**Comment by hellopatrick** [comment]
For example, here's a GIF created (in GIF Brewery 3.4) with Vignette then Process filter, https://gfycat.com/CandidWelloffGeese.

**Comment by euheny** [comment]
ah. good :) thx
